config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'places#index'

  resources :places do |places|
    resources :comments, only: [:create]
    resources :images, only: [:create] do
      resources :attachments
    end
  end

  resources :users, only: :show

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :place
  after_create :send_comment_email

  RATINGS = {
    '1 star' => '1_star',
    '2 stars' => '2_stars',
    '3 stars' => '3_stars',
    '4 stars' => '4_stars',
    '5 stars' => '5_stars'
  }

  def humanized_rating
    RATINGS.invert[self.rating]
  end

  def send_comment_email
    NotificationMailer.comment_added(self).deliver
  end

end

app/models/image.rb
class Image < ActiveRecord::Base
  belongs_to :place
  belongs_to :user
  has_many :images

  mount_uploader :attachment, AttachmentUploader #attachment tells rails to use this uploader


end

app/models/place.rb
class Place < ActiveRecord::Base
  belongs_to :user
  has_many :comments
  has_many :images
  
  geocoded_by :address
  after_validation :geocode

  validates :name, length: {minimum: 3}, presence: true
  validates :address, :description, presence: true

  self.per_page = 10

  def self.search(search, page)
    paginate :per_page => 5, :page => page,
           :conditions => ['name like ?', "%#{search}%"], :order => 'name'
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :places
  has_many :comments 

  def show 
    @user = User.find(params[:id])
  end 

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  before_action :authenticate_user! 

  def create
    @place = Place.find(params[:place_id])
    @place.comments.create(comment_params.merge(user: current_user))
    redirect_to place_path(@place)
  end 

  private 

  def comment_params 
    params.require(:comment).permit(:message, :rating)
  end 

end

app/controllers/image_controller.rb
class ImageController < ApplicationController

  before_action :authenticate_user! 

  def create
    @place = Place.find(params[:place_id])
    @place.images.create(image_params)
    redirect_to place_path(@place)
  end 

  private

    def image_params
      params.require(:image).permit(:attachment, :caption)
    end 

end

app/controllers/images_controller.rb
class ImagesController < ApplicationController

  before_action :authenticate_user!

  def create
    @place = Place.find(params[:place_id]) 
    @place.images.create(image_params)
    redirect_to place_path(@place)
  end 

  private

    def image_params
      params.require(:image).permit(:attachment, :caption)
    end 

end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]

  def index
    @places = Place.paginate(:page => params[:page], :per_page => 10)
  end  

  def new 
    @place = Place.new
  end 

  def create
    @place = current_user.places.create(place_params)
    if @place.valid?
      redirect_to root_path
    else 
      render :new, status: :unprocessable_entity 
    end 
  end 

  def show
    @place = Place.find(params[:id])
    @comment = Comment.new
    @image = Image.new
  end 

  def edit
    @place = Place.find(params[:id])
    if @place.user != current_user
        return render text: 'Not Allowed', status: :forbidden
      end 
  end 

  def update
    @place = Place.find(params[:id])

    if @place.user != current_user
        return render text: 'Not Allowed', status: :forbidden
      end 

    @place.update_attributes(place_params)
    if @place.valid? 
      redirect_to root_path
    else 
      render :edit, status: :unprocessable_entity
    end 
  end 

  def destroy
    @place = Place.find(params[:id])
    if @place.user != current_user
      return render text: 'Not allowed', status: :forbidden
    end 
    @place.destroy
    redirect_to root_path
  end 

  private

  def place_params
    params.require(:place).permit(:name, :description, :address)
  end 

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/image_helper.rb
module ImageHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/images/images.html.erb
<% @place.images.each do |image| %>
  <%= image_tag image.attachment %>
  <%= image.caption %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Palette</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>


  <%= favicon_link_tag 'favicon.ico' %>


<div class="search">
<% form_tag request.path, :method => 'get' do %>
  <% content_tag :label do %>
    Search term:
    <%= text_field_tag :search, params[:search] %>
  <% end %>
<% end %>
</div>

</head>
<body>

<nav class="navbar navbar-inverse" style="margin-bottom:0">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <div class="site-header">
      <a class="navbar-brand" href="/">Palette</a>
      <% link_to root_path %>
      </div>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li>
          <%= link_to new_place_path do %>
          New Place
          <i style="font-size:0.75em;" class="glyphicon glyphicon-plus-sign"></i>
          <% end %>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
          <li><a href="#">About</a></li>
        <% if user_signed_in? %>
          <li><%= link_to 'My Profile', user_path(current_user)%></li>
          <li><%= link_to 'sign out', destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to 'sign in', new_user_session_path %></li>
          <li><%= link_to 'sign up', new_user_registration_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<% if notice.present? %>
  <p class="alert alert-info"><%= notice %></p>
<% end %>
<% if alert.present? %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>

<%= yield %>

<div class="clear"></div>


<div class="col-xs-12 footer">

      <h3>CONTACT</h3>
      <hr class="line"/>
      <br />
      Developed by <a href="http://kathleen-french.getforge.io">Kathleen French</a>
      <br />
      Email - <a href="mailto:kfrench09@gmail.com" target="_blank">here</a>

</div>



</body>
</html>

app/views/places/edit.html.erb
<div class="booyah-box col-xs-10 col-xs-offset-1">
  <h1>Edit Entry</h1>
    <div class="form-style">
    <%= simple_form_for @place do |f| %>
      <%= f.input :name, :input_html => { :class => 'input' } %>
      <br />
      <%= f.input :address, :input_html => { :class => 'input' } %>
      <br />
      <%= f.input :description, :input_html => { :class => 'input-description' } %>
      <br />
      <%= f.submit 'Update', class: 'btn btn-sharp' %>
    <% end %>
     <div class="pull-right">
            <br />
            <% if current_user && current_user == @place.user %>
            <%= link_to 'Remove', place_path(@place), method: :delete, data: {confirm: 'Are you sure you want to delete this?'}, class: 'btn btn-sharp'%>
            <%end%>
            </div>
    </div>
</div>

app/views/places/index.html.erb
<div class="c-wrapper">
<div id="carousel-example-generic" class="carousel slide" data-ride="carousel" style="width:100%">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li style="margin-top:10%" data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
    <li style="margin-top:10%" data-target="#carousel-example-generic" data-slide-to="1"></li>
    <li style="margin-top:10%" data-target="#carousel-example-generic" data-slide-to="2"></li>
    <li style="margin-top:10%" data-target="#carousel-example-generic" data-slide-to="3"></li>
    <li style="margin-top:10%" data-target="#carousel-example-generic" data-slide-to="4"></li>
  </ol>

  <!-- Wrapper for slides -->

  <div class="carousel-inner">
    <div class="item active">
      <%= image_tag 'img_smoke.jpg', class: 'img-responsive' %>
    </div>
    <div class="item">
      <%= image_tag 'img_filet.jpg', class: 'img-responsive' %>
    </div>
      <div class="item">
        <%= image_tag 'img_sushi.jpg', class: 'img-responsive' %>
      </div>
        <div class="item">
        <%= image_tag 'img_egg.jpg' %>
        </div>
    </div>


  <!-- Controls -->
  <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" style="text-align:center"></span>
  </a>
  <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" style="text-align:center"></span>
  </a>


</div>
</div>

<% @places.each do |place| %>
  <div class="booyah-box col-xs-10 col-xs-offset-1" style="margin-top:0">
    <h1><%= link_to place.name, place_path(place), {style:"text-decoration:none; color:black; hover:underline"} %></h1>
    <h5><%= place.address %></h5>

    <div style="width:100%;">
        <div style="float:none; background:none;"> <br/>
        <div class="text-area-description">
          <br />
          <div class="description">
          <p><%= place.description %></p><br/>
        </div>
        </div>
        <div id="container" style="float:right;width:45%;margin-top: -70px; background:url('/assets/pink_rice.png');border-width:10px;border:  background:url('/assets/pink_rice.png');">
        <% if place.images.first %>
            <%= image_tag place.images.first.attachment, class: 'image-tag' %>
        <br />
          <div class="caption" style="text-align:center">
          <%= place.images.first.caption %>
            <br />
          </div>

        <% end %>

        </div>
        </div>

    </div>


<div class="clear"></div>

    <br />
    <%if place.comments.present? %>
    <div class="col-xs-12">
      <blockquote>
        <% if place.comments.last.humanized_rating.present? %>
          <b><%= place.comments.last.humanized_rating %></b> -
          <% end %>
          <%= place.comments.last.message %>
          <small><%= place.comments.last.user.email %></small>
      </blockquote>
      </div>
      <% end %>

      <div class="read-more">
        <%= link_to 'Read More...', place %>
      </div>

  </div>


<% end %>

<div class= "pagination">
  <%= will_paginate @places %>
  <div class="page-text">
      <%= link_to 'First << ', :action => 'index', :page => 1 %>
      <a rel="previous" href="/places?=page=1">Previous - </span>
      <a class="current" href="/places?page=1"> 1 </a>
      <a rel="next" href="/places?page=2">2</a>
      <a href="/places?=page=3">3</a>
      <a href="/places?=page=4">4</a>
      <a class="next_page" rel="next" href="/places?page=2"> - Next</a>
      <%= link_to ' >> Last', :action => 'index', :page => @places.last%>
    </div>
</div>

<script>

$(document).ready(function () {
$( ".container.banner .carousel-inner .item img" ).each(function( index ) {

    X= $(this).width()
    Y= $(this).height()
    margin_left = -(X/2);
    margin_top = -(Y/2);

   $(this).css("margin-left",margin_left + 'px');
   $(this).css("margin-top",margin_top + 'px');
};

)};

</script>

app/views/places/new.html.erb
<div class="booyah-box col-xs-10 col-xs-offset-1">
 <div class="simple-form">
  <h1>Enter Your Place Details</h1>
    <br />
    <div class="form-style" class="field">
        <%= simple_form_for @place do |f| %>
          <%= f.input :name, :input_html => { :class => 'input' } %>
        <br />
          <%= f.input :address, :input_html => { :class => 'input' } %>
        <br />
          <%= f.input :description, :input_html => { :class => 'input-description' } %>
        <br />
      <%= f.submit :class => 'btn btn-sharp-upload' %>
      <br />
      <br />
      <%end%>
      <br />
      <br />
    </div>
  </div>



<!-- Photo Uploader -->

app/views/places/show.html.erb
<div class="booyah-box col-xs-10 col-xs-offset-1">


  <h1><%= @place.name %></h1>
<i><h5><%= @place.address %></h5><br/></i>

  <% if @place.latitude.present? && @place.longitude.present? %>
      <div style="width:100%;">
          <div style="float:none; background:none;"> <br/>
          <div class="text-area-description">
            <h3>About</h3>
            <br />
            <div class="description">
            <p><%= @place.description %></p><br/>
          </div>
          </div>

          <div id="container" style="float:right;width:50%;margin-top: -70px;margin-right:-20px; background:none;">
            <div class="booyah-box col-xs-10 col-xs-offset-1">
            <% if @place.images.last %>
              <%= image_tag @place.images.last.attachment, class: 'image-tag' %>
                  <br />
                  <br />
              <div class="caption">
                <%= @place.images.last.caption %>
              </div>
                 <% end %>
              </div>
              <div class="clear"></div>

          </div>
          </div>

      </div>


<div class="clear"></div>

<!-- Social Share -->

<div class="social-share"style="text-align:right;margin-right:5px">
<a class="btn btn-social-icon btn-facebook"href="http://www.facebook.com/sharer.php?u=http://www.pontikis.net"
	target="_blank">
  <span class="fa fa-facebook"></span>
</a>
<a class="btn btn-social-icon btn-twitter"href="http://twitter.com/share?text=An%20intersting%20blog&url=http://www.pontikis.net"
	target="_blank">
  <span class="fa fa-twitter"></span>
</a>
<a class="btn btn-social-icon btn-google"href="https://plus.google.com/share?url=http://www.pontikis.net"
	target="_blank">
  <span class="fa fa-gooogle"></span>
</a>
</div>

<!-- Button trigger Gallery Modal -->

<br />
<button class="btn btn-sharp-gallery"style="margin-right:5px" data-toggle="modal" data-target="#myModalGallery">
  See Gallery
</button>
<div class="clear"></div>


<!-- Gallery Modal -->

    <div class="modal fade-gallery" id="myModalGallery" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
      <div class="modal-dialog-gallery">
        <div class="modal-content">
          <div class="modal-header">

   <h2> Gallery </h2>
    <% @place.images.in_groups_of(3) do |group| %>
    <div class="row">
      <% group.compact.each do |image| %>
        <div class="col-xs-4">
          <%= image_tag image.attachment, :width => '100%' if image.attachment.present? %>
          <h4><% link_to image.caption, image %></h4>
          <%= image.caption %>
          </div>
        <%end%>
        </div>
        <%end%>
        <div class="clear"></div>
        <br />
        <br />
            <button type="button" class="btn btn-sharp" data-dismiss="modal">Close</button>
  <!-- Button trigger Add Photo -->
              <button class="btn btn-sharp-upload" data-toggle="modal" data-target="#myModalImage">
              Add a Photo
            </button>
          </div>

    <!-- New Photo Modal -->
  <div class="clear"?></div>
    <div class="modal fade" id="myModalImage" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            <h4 class="modal-title" id="myModalLabel">Add a Photo:</h4>
          </div>

  <!-- PHOTO UPLOAD -->

      <div class="simple-form">
      <%= simple_form_for @image, url: place_images_path(@place) do |f| %>
        <div class="modal-body">
        <div class="image-section" class="form-style">
        <div class="image-message">
              <%= f.input :caption %>
              <%= f.input :attachment %>
        </div>
            <div class="modal-footer">
                <br />
            <div class="clear"></div>
            <br/>
                <button type="button" class="btn btn-sharp" data-dismiss="modal">Close</button>
                <%= f.submit 'Submit', class: 'btn btn-sharp' %>
                <%end%>
            </div>
        </div>
        </div>
        </div>
            <br />
            <br/>
      </div>
    </div>
  <br />
  <br />

<!-- -->

            </div>
            <div class="clear"></div>
        </div>
      </div>
    </div>
  <br />
  <br />


<!-- Map -->

    <div id="map">
    <script>
      function initMap() {
        // Styles a map in night mode.
        var myLatLng = {lat: <%= @place.latitude %>, lng: <%= @place.longitude %>};

        var map = new google.maps.Map(document.getElementById('map'), {
          center: myLatLng,
          zoom: 15,
          scrollwheel: false,
          styles: [
            {elementType: 'geometry', stylers: [{color: '#242f3e'}]},
            {elementType: 'labels.text.stroke', stylers: [{color: '#242f3e'}]},
            {elementType: 'labels.text.fill', stylers: [{color: '#746855'}]},
            {
              featureType: 'administrative.locality',
              elementType: 'labels.text.fill',
              stylers: [{color: '#d59563'}]
            },
            {
              featureType: 'poi',
              elementType: 'labels.text.fill',
              stylers: [{color: '#d59563'}]
            },
            {
              featureType: 'poi.park',
              elementType: 'geometry',
              stylers: [{color: '#263c3f'}]
            },
            {
              featureType: 'poi.park',
              elementType: 'labels.text.fill',
              stylers: [{color: '#6b9a76'}]
            },
            {
              featureType: 'road',
              elementType: 'geometry',
              stylers: [{color: '#38414e'}]
            },
            {
              featureType: 'road',
              elementType: 'geometry.stroke',
              stylers: [{color: '#212a37'}]
            },
            {
              featureType: 'road',
              elementType: 'labels.text.fill',
              stylers: [{color: '#9ca5b3'}]
            },
            {
              featureType: 'road.highway',
              elementType: 'geometry',
              stylers: [{color: '#746855'}]
            },
            {
              featureType: 'road.highway',
              elementType: 'geometry.stroke',
              stylers: [{color: '#1f2835'}]
            },
            {
              featureType: 'road.highway',
              elementType: 'labels.text.fill',
              stylers: [{color: '#f3d19c'}]
            },
            {
              featureType: 'transit',
              elementType: 'geometry',
              stylers: [{color: '#2f3948'}]
            },
            {
              featureType: 'transit.station',
              elementType: 'labels.text.fill',
              stylers: [{color: '#d59563'}]
            },
            {
              featureType: 'water',
              elementType: 'geometry',
              stylers: [{color: '#17263c'}]
            },
            {
              featureType: 'water',
              elementType: 'labels.text.fill',
              stylers: [{color: '#515c6d'}]
            },
            {
              featureType: 'water',
              elementType: 'labels.text.stroke',
              stylers: [{color: '#17263c'}]
            }
          ]
        });

        var marker = new google.maps.Marker ({
          position: myLatLng,
          map: map,
        });
      }
    </script>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyARiezVR2lQ-UrD1d00e58KHsu91UmxGVw&callback=initMap"
    async defer></script>
  <% end %>
</div>

  <br />

<div class="clear"></div>

  <!-- Edit, Email -->
  <br />
 <div class="pull-right">
    <% if current_user && current_user == @place.user %>
    <%= link_to 'Edit', edit_place_path(@place) %>
    <%end%>
  <br />
  <% if @place.user.present? %>
      <email><%= @place.user.email %></email>
  <% end %>

  </div>

  <div class="clear"></div>

  <br />
  <!-- Button trigger modal comments-->
    <button class="btn btn-sharp-leave" data-toggle="modal" data-target="#myModalComment">
      Leave a Comment
    </button>

    <div class="clear"?></div>

    <!-- Modal -->
    <div class="modal fade" id="myModalComment" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            <h4 class="modal-title" id="myModalLabel">Add a comment:</h4>
          </div>

    <!-- Add New Comment -->

    <div class="simple-form">

      <%= simple_form_for @comment, url: place_comments_path(@place) do |f| %>
        <div class="modal-body">
        <div class="comment-section" class="form-style">
        <div class="comment-message">
              <%= f.input :message %>
              <%= f.input :rating, as: :select, collection: Comment::RATINGS %>
        </div>
        <div class="modal-footer-commen">
        <br />
            <div class="clear"></div>
            <div class="btn btn-sharp-upload">
                <%= f.submit 'Submit', class: 'btn btn-sharp-upload' %>
                  <%end%>
                <br /
                <br />
            </div>
        </div>

        </div>
        </div>

    </div>

<!-- -->

    <div class="clear"></div>

        </div>
      </div>
    </div>
  <br />
  <br />


  <!--  Comment Section -->

  <div class="comment-footer"> <h3>Comments</h3></div>
  <hr class="line"/>
  <br />
  <br />

    <% @place.comments.each do |comment| %>
      <div class="col-xs-12 col-sm-6">
      <blockquote>
        <% if comment.humanized_rating.present? %>
          <b><%= comment.humanized_rating %></b> -
          <% end %>
          <%= comment.message %>
          <br />
          <small><%= comment.user.email %></small>
      </blockquote>
      </div>
    <% end %>
    </div>


</div>

app/views/users/show.html.erb
<div class="booyah-box">
  <div class="col-xs-4">
    <%= image_tag 'user.png', {style:"width:90%;height:auto"} %>
    <!--creates an 20x20 pixel-->
    <img><%= gravatar_tag @user.email, :size => 20 %></img>
  </div>

<div class="col-xs-8">
        <p>user e-mail: <%= @user.email %></p>
        <p>Member Since: <%= @user.created_at.strftime("%B %d, %Y") %></p>
        <p><%= @user.comments.count %> total comments </p>
        <p><%= @user.comments.where(rating:'5_stars').count %> total 5 star reviews </p>
</div>

<div class="clear"></div>
<br /><br />

<!-- my comments -->

<h2 class="text-center">My Comments</h2>
<br /><br />
<% @user.comments.each do |comment| %>

  <div class="col-xs-12 col-sm-6">
    <h3><%= link_to comment.place.name, place_path(comment.place), {style:"text-decoration:none;color:black;hover:underline"} %></h3><br/>
    <blockquote>
      <% if comment.humanized_rating.present? %>
        <b><%= comment.humanized_rating %></b> -
      <% end %>
      <%= comment.message %>
      <small><%= comment.user.email %></small>
    </blockquote>
  </div>
<% end %>
<br/>

<div class="clear"></div>

<!-- my places -->

<div class="my-places">
<h2 class="text-center"> My Places </h2>
<br/>
  <% @user.places.each do |place| %>
      <h3><%= link_to place.name, place_path(place), {style:"text-decoration:none;color:black;hover:underline"} %></h3>
      <br/>
      <i><%= place.address %></i>
      <br/>
      <p><%= place.description %></p><br />
  <% end %>
</div>
</div>